apiVersion: v1
kind: ConfigMap
metadata:
  name: group-service-config
  namespace: habitmap
data:
  PORT: "3003"
  NODE_ENV: "production"
  AUTH_SERVICE_URL: "http://auth-service.habitmap.svc.cluster.local:3001"
  HABIT_SERVICE_URL: "http://habit-service.habitmap.svc.cluster.local:3002"
