apiVersion: v1
kind: Service
metadata:
  name: group-service
  namespace: habitmap
  labels:
    app: group-service
spec:
  type: ClusterIP
  selector:
    app: group-service
  ports:
    - name: http
      port: 3003
      targetPort: 3003
      protocol: TCP
