apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: habitmap
data:
  PORT: "3004"
  NODE_ENV: "production"
  HABIT_SERVICE_URL: "http://habit-service.habitmap.svc.cluster.local:3002"
  AUTH_SERVICE_URL: "http://auth-service.habitmap.svc.cluster.local:3001"
  GROUP_SERVICE_URL: "http://group-service.habitmap.svc.cluster.local:3003"
