apiVersion: v1
kind: Namespace
metadata:
  name: habitmap
  labels:
    app.kubernetes.io/part-of: habitmap
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    app.kubernetes.io/part-of: habitmap
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: habitmap
